# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'System_size.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from ui2 import Ui_MaxInput

resN = None
procN = None
class Ui_DataInput1(object):

    def setupUi(self, DataInput1):
        DataInput1.setObjectName("DataInput1")
        #DataInput1.resize(600, 500)
        #DataInput1.resize(600, 500)
        DataInput1.setGeometry(500,100,500,500)
        self.pushButton = QtWidgets.QPushButton(DataInput1)
        self.pushButton.setGeometry(QtCore.QRect(110, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(DataInput1)
        self.lineEdit.setGeometry(QtCore.QRect(220, 70, 41, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(DataInput1)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 120, 41, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(DataInput1)
        self.label.setGeometry(QtCore.QRect(20, 90, 250, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DataInput1)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.DataInput1 = DataInput1
        self.retranslateUi(DataInput1)
        QtCore.QMetaObject.connectSlotsByName(DataInput1)

    def retranslateUi(self, DataInput1):
        _translate = QtCore.QCoreApplication.translate
        DataInput1.setWindowTitle(_translate("DataInput1", "System Size"))
        self.pushButton.setText(_translate("DataInput1", "Next"))
        self.label.setText(_translate("DataInput1", "Number of Processes"))
        self.label_2.setText(_translate("DataInput1", "Number of Resources"))


    def next_clicked(self):
        global procN, resN
        procN = int(self.lineEdit.text())
        resN = int(self.lineEdit_2.text())
        self.MaxInput = QtWidgets.QDialog()
        self.ui = Ui_MaxInput()
        self.ui.setupUi(self.MaxInput, procN, resN)
        self.MaxInput.show()
        self.DataInput1.hide()

        self.ui.pushButton.clicked.connect(self.ui.enter_clicked)



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    DataInput1 = QtWidgets.QDialog()
    ui = Ui_DataInput1()
    ui.setupUi(DataInput1)
    DataInput1.show()

    ui.lineEdit.setValidator(QIntValidator(0, 100))
    ui.lineEdit_2.setValidator(QIntValidator(0, 100))
    ui.pushButton.clicked.connect(ui.next_clicked)

    sys.exit(app.exec_())
