# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alloc_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
from ui4 import Ui_TotalInput

Alloc = None

class Ui_AllocInput(object):
    def setupUi(self, AllocInput, pNum, rNum):
        global Alloc
        self.procN = pNum
        self.resN = rNum
        Alloc = np.empty((int(self.procN), int(self.resN)), int)
        AllocInput.setObjectName("AllocInput")
        AllocInput.resize(363, 448)
        self.pushButton = QtWidgets.QPushButton(AllocInput)
        self.pushButton.setGeometry(QtCore.QRect(140, 390, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(AllocInput)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 321, 301))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(self.resN)
        self.tableWidget.setRowCount(self.procN)
        self.label = QtWidgets.QLabel(AllocInput)
        self.label.setGeometry(QtCore.QRect(110, 20, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.AllocInput = AllocInput
        self.retranslateUi(AllocInput)
        QtCore.QMetaObject.connectSlotsByName(AllocInput)

    def retranslateUi(self, AllocInput):
        _translate = QtCore.QCoreApplication.translate
        AllocInput.setWindowTitle(_translate("AllocInput", "Allocation Input"))
        self.pushButton.setText(_translate("AllocInput", "Enter"))
        self.label.setText(_translate("AllocInput", "Current Allocation"))

    def enter_clicked(self):
        global Alloc
        for row in range(self.tableWidget.rowCount()):
            for column in range(self.tableWidget.columnCount()):
                Alloc[row, column] = int(self.tableWidget.item(row, column).text())
        self.loadNext()

    def loadNext(self):
        self.Total_input = QtWidgets.QDialog()
        self.ui = Ui_TotalInput()
        self.ui.setupUi(self.Total_input, self.resN)
        self.Total_input.show()
        self.AllocInput.hide()

        self.ui.pushButton.clicked.connect(self.ui.enter_clicked)