# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'total_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
from ui5 import Ui_Update

Total = None

class Ui_TotalInput(object):
    def setupUi(self, TotalInput, resN):
        global Total
        Total = np.empty((1, int(resN)), int)
        TotalInput.setObjectName("TotalInput")
        TotalInput.resize(363, 313)
        self.pushButton = QtWidgets.QPushButton(TotalInput)
        self.pushButton.setGeometry(QtCore.QRect(140, 250, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(TotalInput)
        self.tableWidget.setGeometry(QtCore.QRect(20, 80, 321, 121))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(resN)
        self.tableWidget.setRowCount(1)
        self.label = QtWidgets.QLabel(TotalInput)
        self.label.setGeometry(QtCore.QRect(110, 30, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.TotalInput = TotalInput
        self.retranslateUi(TotalInput)
        QtCore.QMetaObject.connectSlotsByName(TotalInput)

    def retranslateUi(self, TotalInput):
        _translate = QtCore.QCoreApplication.translate
        TotalInput.setWindowTitle(_translate("TotalInput", "Total input"))
        self.pushButton.setText(_translate("TotalInput", "Enter"))
        self.label.setText(_translate("TotalInput", "Total Resources"))

    def enter_clicked(self):
        global Total
        for column in range(self.tableWidget.columnCount()):
            Total[0, column] = int(self.tableWidget.item(0, column).text())
        self.loadNext()

    def loadNext(self):
        self.Update = QtWidgets.QDialog()
        self.ui = Ui_Update()
        self.ui.setupUi(self.Update)
        self.Update.show()
        self.TotalInput.hide()

        self.ui.pushButton.clicked.connect(self.ui.enter_clicked)