# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui6 import Ui_Result

pNum = rNum = number = 0

class Ui_Update(object):
    def setupUi(self, Update):
        Update.setObjectName("Update")
        Update.resize(504, 186)
        self.label = QtWidgets.QLabel(Update)
        self.label.setGeometry(QtCore.QRect(40, 40, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Update)
        self.label_2.setGeometry(QtCore.QRect(340, 40, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Update)
        self.label_3.setGeometry(QtCore.QRect(180, 40, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Update)
        self.lineEdit.setGeometry(QtCore.QRect(50, 80, 41, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Update)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 80, 41, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Update)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 80, 41, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(Update)
        self.pushButton.setGeometry(QtCore.QRect(200, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.Update = Update
        self.retranslateUi(Update)
        QtCore.QMetaObject.connectSlotsByName(Update)

    def retranslateUi(self, Update):
        _translate = QtCore.QCoreApplication.translate
        Update.setWindowTitle(_translate("Update", "Update Data"))
        self.label.setText(_translate("Update", "Process #"))
        self.label_2.setText(_translate("Update", "How much?"))
        self.label_3.setText(_translate("Update", "Resource #"))
        self.pushButton.setText(_translate("Update", "Enter"))


    def enter_clicked(self):
        global pNum, rNum, number
        pNum = int(self.lineEdit.text())
        rNum = int(self.lineEdit_2.text())
        number = int(self.lineEdit_3.text())
        self.loadNext()

    def loadNext(self):
        self.Result = QtWidgets.QDialog()
        self.ui = Ui_Result()
        self.ui.setupUi(self.Result)
        self.Result.show()
        self.Update.hide()
