# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'answer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main import Banker

class Ui_Result(object):
    def setupUi(self, Result):
        Result.setObjectName("Result")
        Result.resize(400, 300)
        self.label = QtWidgets.QLabel(Result)
        self.label.setGeometry(QtCore.QRect(50, 40, 311, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.retranslateUi(Result)
        QtCore.QMetaObject.connectSlotsByName(Result)

        self.getAnswer()

    def retranslateUi(self, Result):
        _translate = QtCore.QCoreApplication.translate
        Result.setWindowTitle(_translate("Result", "Answer"))
        self.label.setText(_translate("Result", "TextLabel"))


    def getAnswer(self):
        banker = Banker()
        seq = banker.is_safe_state()
        if(seq != []):
            st = "It's Safe Request:\n"
            for item in seq:
                st += " P" + str(item)
            self.label.setText(st)
        else:
            self.label.setText("It's Unsafe Request")